//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRent
    {
        public BookRent()
        {
            this.RentBookDetails = new HashSet<RentBookDetail>();
        }
    
        public long RentID { get; set; }
        public long MemberId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<int> NumberOfDay { get; set; }
    
        public virtual ICollection<RentBookDetail> RentBookDetails { get; set; }
        public virtual Member Member { get; set; }
    }
}
