//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.RentBookDetails = new HashSet<RentBookDetail>();
        }
    
        public long BookID { get; set; }
        public string BookName { get; set; }
        public string BookCode { get; set; }
        public string ISBN { get; set; }
        public string Author { get; set; }
        public long CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<RentBookDetail> RentBookDetails { get; set; }
    }
}
