//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentBookDetail
    {
        public long RentDetailID { get; set; }
        public long RentID { get; set; }
        public long BookID { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual BookRent BookRent { get; set; }
    }
}
